### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by Papito8z** [VincentAuriau/Tennis-Prediction#17]
Hello, can you explain to me how to launch your application? And how can I effectively analyze a match?

**Comment by VincentAuriau** [comment]
Hello,
The repository does'nt really aim at analyzing a single match.
The goal is to create at match time the most insighful statistics (e.g. players win ratios, player wins ratio against each other, players win ratio on different court type, etc...) berfore the match.

In order to use the repo, you need to clone it 

```bash
git clone --recurse-submodules https://github.com/VincentAuriau/Tennis-Prediction.git
```

Installing basic libraries (pandas, numpy, etc...) you can use python to load the data as shown in example:

```python
from data.data_loader import matches_data_loader
data_df = matches_data_loader(path_to_data="submodules/tennis_atp")
```

I do not have a detailed list of all the statistics, for now it is pretty basic. However you can use the structure to compute yours.
